"""Add gallery images table

Revision ID: 7575707770e7
Revises: 9f3c56c8c3fc
Create Date: 2025-10-31 14:27:31.243927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7575707770e7'
down_revision = '9f3c56c8c3fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['uploaded_by'], ['id'])

    with op.batch_alter_table('membership_application', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('membership_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('gallery_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('branch_activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
