"""Add video and audio fields to posts

Revision ID: 9f3c56c8c3fc
Revises: 5272c60f6ae3
Create Date: 2025-10-31 11:58:54.108780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3c56c8c3fc'
down_revision = '5272c60f6ae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch_activity', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])

    with op.batch_alter_table('membership_application', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audio_filename', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('audio_filename')
        batch_op.drop_column('video_filename')
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('membership_application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('branch_activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
